### PR TITLE
Tedx/features/page/team

### LINKED ISSUE #12: Make a Team page
- [x] Pull Develop Branch so that you have the latest code
- [x] Create a branch called `tedx/features/page/{pageName}` (in lowercase filename but Capitalcase Function Name)
- [x] Add your code
- [x] Create a PR
- [x] Link this Issue in your PR
- [x] Add me @pruthvi2103  to the Reviewers list so that you can request a review
- [x] message in the tasks channel

### PR DESCRIPTION
**Pull request by ZeffK**
#12

### CODE REVIEW

**Comment by ZeffK** [comment]
added team page

**Review by pruthvi2103 — CHANGES_REQUESTED** [review]
Change Function Name to `Team` from `team`

**Review by pruthvi2103 — APPROVED** [review]
LGTM

**Review by sohamtamboli — COMMENTED** [review]
No suggestions for change

**Pull request merged**
